GOOGLE_API_KEY = "AIzaSyBXyQcWuy487SR68o6pOx2nAkhGV1hdET4"
TELEGRAM_BOT_TOKEN = "8407012299:AAHE8O_SrVwu54dLYDnawhQzvOKwaBsGMqQ"
TELEGRAM_CHAT_ID = "902599285"
DB_URL = "postgresql://postgres.hipnauvtegiqnarmsixc:KebabGaming007@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"
SMTP_EMAIL = "hankebabgaming@gmail.com"
SMTP_PASSWORD = "lsnf gsgf okph lzot"